name: tune_sam
version: ISTD+_lora_mseloss_1e-1contGradnoPenumbra_version_24
phase: train
samshadow_ckpt_path: ./experiments_lightning/tune_sam/ISTD+_lora_mseloss_1e-1contGradnoPenumbra_version_24/epoch=99.ckpt
save_result_path: ./experiments_lightning/tune_sam/ISTD+_lora_mseloss_1e-1contGradnoPenumbra_version_24/99_to_train_diffusion


grad_loss_weight: 0.1
loss_type: mse+constrain
constrain: noPenumbra
patch_tricky: false

datasets:
  train:
    name: SRD_sam_train
    mode: HR
    dataroot: ./dataset/ISTD_adjusted_C/train
    gt_mask_dir: ./dataset/ISTD_adjusted_C/train/train_B
    batch_size: 2
    num_workers: 8
    use_shuffle: true
  test:
    name: SRD_sam_val
    mode: LRHR
    dataroot: ./dataset/ISTD_adjusted_C/train
    gt_mask_dir: ./dataset/ISTD_adjusted_C/train/train_B
    batch_size: 1
    data_len: -1

train:
  gpu_ids: [0,1,2,3]
  accumulate_grad_batches: 2
  max_epochs: 100
  every_n_epochs: 50

test:
  gpu_ids: [0]


ckpt_path:
#  'sam_adapter': ./experiments/official_test/SAM_adapter_ckpt/model_epoch_best.pth
  'ddpm': ./experiments/official_test/checkpoint/SRD_dataset/I2130000_E12080 # two ckpts share same name
  'SAM': "./experiments/official_test/SAM_ckpt/sam_vit_h_4b8939.pth"

bbox_path: "./dataset/ISTD_adjusted_C/train/bounding_boxes_ISTD.yaml"
test_bbox_path: "./dataset/ISTD_adjusted_C/train/bounding_boxes_ISTD.yaml"
model_type: "vit_h"
sam_rank: 8


