name: tune_sam
version: lora_mseloss_1tvloss_5e-1gradloss_version_5
phase: test
samshadow_ckpt_path: /home/xinrui/projects/ShadowDiffusion/experiments_lightning/tune_sam/lora_mseloss_1tvloss_5e-1gradloss_version_5/epoch=49.ckpt
save_result_path: /home/xinrui/projects/ShadowDiffusion/experiments_lightning/tune_sam/lora_mseloss_1tvloss_5e-1gradloss_version_5/49_to_test_diffusion

#unfreeze_sam_head: False
#detach_sam: True
#diffusion_scale: 1
tv_loss_beta: 1
grad_loss_weight: 5e-1

datasets:
  train:
    name: SRD_sam_train
    mode: HR
    dataroot: ./dataset/SRD_sam_mask_B/train
    gt_file_name: division_filter_results # residual mask
    batch_size: 1
    num_workers: 8
    use_shuffle: true
  test:
    name: SRD_sam_val
    mode: LRHR
    dataroot: ./dataset/SRD_sam_mask_B/test
    gt_file_name: division_filter_results
    batch_size: 1
    data_len: -1

train:
  gpu_ids: [2, 3]
  accumulate_grad_batches: 8
  max_epochs: 50
  every_n_epochs: 10

test:
  gpu_ids: [2]

warmup_epochs: 10
max_epochs: 200

ckpt_path:
  'sam_adapter': ./experiments/official_test/SAM_adapter_ckpt/model_epoch_best.pth
  'ddpm': ./experiments/official_test/checkpoint/SRD_dataset/I2130000_E12080 # two ckpts share same name
  'SAM': "./experiments/official_test/SAM_ckpt/sam_vit_h_4b8939.pth"

bbox_path: "./dataset/SRD_sam_mask_B/train/bounding_boxes_DHAN.yaml"
test_bbox_path: "./dataset/SRD_sam_mask_B/test/bounding_boxes_DHAN.yaml"
model_type: "vit_h"
sam_rank: 8


