name: tune_sam+diffusion
version: Patch_detach_mse+1e-1contGradnoPenumbra_version_2.1
phase: train
samshadow_ckpt_path: ./experiments_lightning/tune_sam+diffusion/image_gt_ISTD_lora_mseloss_1e-1contGradnoPenumbra_fromISTD+_version_24.2/epoch=499.ckpt
#samshadow_ckpt_path: ./experiments_lightning/tune_sam+diffusion/image_lora_sam_mse_1e-4orientation_version_20/epoch=499.ckpt
save_result_path: ./experiments_lightning/tune_sam+diffusion/image_gt_ISTD_lora_mseloss_1e-1contGradnoPenumbra_fromISTD+_version_24.2/499
resume: false
resume_path: ./

patch_tricky: true
h_hat: false

datasets:
  train:
    name: SRD_sam_train
    mode: HR
    dataroot: ./dataset/SRD_sam_mask_B/train
    gt_mask_dir: ./experiments_lightning/tune_sam+diffusion/Patch_detach_mse+1e-1contGradnoPenumbra_version_2/train_to_diffusion
#    gt_mask_dir: ./dataset/ISTD_adjusted_C/train/train_B
    batch_size: 4
    val_data_len: 4
    num_workers: 8
    use_shuffle: true
  test:
    name: SRD_sam_val
    mode: LRHR
    dataroot: ./dataset/SRD_sam_mask_B/test
    gt_mask_dir: ./experiments_lightning/tune_sam/ISTD+_lora_mseloss_1e-1contGradnoPenumbra_version_24/99_to_test_diffusion/check_mask
#    gt_mask_dir: ./dataset/ISTD_adjusted_C/test/test_B
    data_len: -1
    batch_size: 1

model:
  which_model_G: sr3
  unet:
    in_channel: 7
    out_channel: 3
    inner_channel: 64
    norm_groups: 16
    channel_multiplier:
      - 1
      - 2
      - 4
      - 8
    attn_res:
      - 16
    res_blocks: 2
    dropout: 0
  beta_schedule:
    train:
      schedule: linear
      n_timestep: 1000
      linear_start: 1e-4
      linear_end: 0.02
    val:
      schedule: linear
      n_timestep: 1000
      linear_start: 1e-4
      linear_end: 0.02
  diffusion:
    image_size: 512
    channels: 3
    conditional: true

#sam:
#  input_size: 1024
#  loss: iou

train:
  gpu_ids: [0,1]
  accumulate_grad_batches: 1
  max_epochs: 1000
  every_n_epochs: 100
  optimizer:
    lr: 3e-5

test:
  gpu_ids: [0]

warmup_epochs: 10


ckpt_path:
  'lora_sam': ./experiments_lightning/tune_sam/ISTD+_lora_mseloss_1e-1contGradnoPenumbra_version_24/epoch=99.ckpt
#  'ddpm': ./experiments/official_test/checkpoint/SRD_dataset/I2130000_E12080 # two ckpts share same name
  'ddpm': ./experiments/official_test/checkpoint/SRD_dataset/I2130000_E12080
  'SAM':  "./experiments/official_test/SAM_ckpt/sam_vit_h_4b8939.pth"

bbox_path: "./dataset/SRD_sam_mask_B/train/bounding_boxes_DHAN.yaml"
test_bbox_path: "./dataset/SRD_sam_mask_B/test/bounding_boxes_DHAN.yaml"
model_type: "vit_h"
sam_rank: 8